package br.com.ioblue.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "accounts")
public class Account {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private String category;

	@DynamoDBAttribute
	private String description;
	
	@DynamoDBAttribute
	private Integer agency;
	
	@DynamoDBAttribute
	private Integer number;

	@DynamoDBAttribute
	private String doc;

	@DynamoDBAttribute
	private String type;

	@DynamoDBAttribute
	private boolean active;

}